parameter_defaults:
    InternalApiNetCidr: 172.17.1.0/24
    StorageNetCidr: 172.17.3.0/24
    StorageMgmtNetCidr: 172.17.4.0/24
    TenantNetCidr: 172.17.2.0/24
    ExternalNetCidr: 192.168.10.0/24
    InternalApiAllocationPools: [{'start': '172.17.1.10', 'end': '172.17.1.200'}]
    StorageAllocationPools: [{'start': '172.17.3.10', 'end': '172.17.3.200'}]
    StorageMgmtAllocationPools: [{'start': '172.17.4.10', 'end': '172.17.4.200'}]
    TenantAllocationPools: [{'start': '172.17.2.10', 'end': '172.17.2.200'}]
    ExternalAllocationPools: [{'start': '192.168.10.64', 'end': '192.168.10.95'}]
    ExternalInterfaceDefaultRoute: 192.168.10.1
    InternalApiNetworkVlanID: 2001
    StorageNetworkVlanID: 2002
    StorageMgmtNetworkVlanID: 2003
    ExternalNetworkVlanID: 10
    TenantNetworkVlanID: 2004
    NeutronExternalNetworkBridge: "''"
    ControlPlaneSubnetCidr: "24"
    ControlPlaneDefaultRoute: 172.31.255.1
    EC2MetadataIp: 172.31.255.1
    DnsServers: ["8.8.8.8", "8.8.4.4",]

